
package frc.robot.auto;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj LeftSideStart = new ChoreoTraj(
	    "LeftSideStart",
	    OptionalInt.empty(),
	    8.54962,
	    new Pose2d(3.555, 7.461, Rotation2d.fromRadians(0)),
	    new Pose2d(1.134, 5.184, Rotation2d.fromRadians(-1.162))
	);
	public static final ChoreoTraj RightSideStart = new ChoreoTraj(
	    "RightSideStart",
	    OptionalInt.empty(),
	    1.14316,
	    new Pose2d(3.656, 0.608, Rotation2d.fromRadians(0)),
	    new Pose2d(7.079, 1.564, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj MidSideStart = new ChoreoTraj(
	    "MidSideStart",
	    OptionalInt.empty(),
	    1.36586,
	    new Pose2d(3.656, 4.056, Rotation2d.fromRadians(0)),
	    new Pose2d(0.459, 0.683, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("LeftSideStart", LeftSideStart),
		Map.entry("RightSideStart", RightSideStart),
		Map.entry("MidSideStart", MidSideStart)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
