name: Enforce style
on: [pull_request, workflow_dispatch]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # keep ref if you need to checkout the PR head branch explicitly
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Run google-java-format
        uses: axel-op/googlejavaformat-action@v4.0.0
        with:
          args: "--aosp --replace"
